// Shared content types for the public site and the CMS.
// Kept free of any server-only imports so both client and server can use them.

export type IconName =
  | "Building2"
  | "PartyPopper"
  | "Package"
  | "Plane"
  | "Video"
  | "Smartphone";

export type Seo = {
  title: string;
  description: string;
};

export type Service = {
  slug: string;
  title: string;
  icon: IconName;
  tagline: string;
  description: string;
  longDescription: string;
  image: string;
  gallery: string[];
  order: number;
  visible: boolean;
  seo?: Seo;
};

/** A user-created page whose body (with layout) is generated by AI. */
export type CustomPage = {
  id: string;
  title: string;
  slug: string;
  html: string;
  visible: boolean;
  showInNav: boolean;
  order: number;
  seo: Seo;
};

export type ProcessStep = {
  step: string;
  title: string;
  description: string;
};

export type PagesContent = {
  hero: {
    headline: string;
    tagline: string;
    cta_label: string;
    cta_url: string;
  };
  about: {
    heading: string;
    body: string;
    photo: string;
  };
  process: ProcessStep[];
  contact: {
    email: string;
    phone: string;
    location: string;
    instagram: string;
    linkedin: string;
  };
  seo: {
    site_name: string;
    default_description: string;
    default_og_image: string;
  };
};

export type NavLink = { label: string; href: string };

// The editable JSON content files. Used to whitelist API `:file` params.
export type ContentFile = "services" | "pages" | "custom-pages";
export const CONTENT_FILES: ContentFile[] = ["services", "pages", "custom-pages"];

export type Stage = "published" | "draft";
